import {Certification} from "@/app/types/dataType";
import {Education} from "@/app/types/dataType";
import {Internship} from "@/app/types/dataType";
import {
    SiSpringboot, SiSpring,
    SiReact, SiNextdotjs, SiAngular, SiTypescript,
    SiDocker, SiGit,
    SiMysql,
    SiSwagger,
} from 'react-icons/si';
import { FaJava } from 'react-icons/fa';
import { TbBrandOpenai, TbApi, TbBrandAws } from 'react-icons/tb';


 export const projects = [
        {
            title: 'DigitalOcean Gradient™ AI Hackathon : AI Technical Interview Simulator For Software Engineers - IntervAI',
            description: 'IntervAI is an AI-powered technical interview simulator built with Spring Boot, Spring AI, and Angular. It lets developers practice interviews tailored to a specific role, tech stack, and difficulty level, with three distinct AI interviewer personas, a strict FAANG-style interviewer, a startup CTO, and a junior-friendly mentor. Each session generates adaptive questions in real time, preserves full conversation history across 8 rounds, and ends with a structured AI evaluation covering score, strengths, weaknesses, and improvement suggestions. Sessions are time-bound, resumable after disconnection, and all results are stored for progress tracking. The backend is secured with Spring Security + JWT, connected to a managed MySQL database, and the full stack is deployed on DigitalOcean App Platform.',
            tags: ['Spring Boot', 'Spring AI', 'Docker', 'REST API','DigitalOcean Gradient AI', 'Cloud','MySQL', 'TypeScript','Angular', 'CSS', 'Spring Security', 'UML'],
            screenshots: [
                '/projects/video/demo1.mp4',
            ],
            architecture: [
                '/projects/architectures/arch1.jpg'
            ],
            github: 'https://github.com/HajarAitAbdielmomin/AI-Technical-Interview-Simulator-for-software-engineers', live: '#',
        },
     {
         title: 'End-to-End Digital Selection & Admission System of ENSA',
         description: 'A digital platform designed to modernize and streamline the student selection and admission process at engineering schools. It replaces time-consuming manual procedures with a centralized and efficient system for managing applications, evaluating candidates, and processing admission results, improving speed, transparency, accuracy, and fairness throughout the admission journey.',
         tags: ['Java', 'Spring Boot', 'TypeScript','Spring Security','CSS','Angular', 'MongoDB', 'Docker', 'Bizagi', 'BPMN', 'Docker-compose', 'UML'],
         screenshots: [
             '/projects/screenshot/screenshots3/img.png',
             '/projects/screenshot/screenshots3/img_1.png',
             '/projects/screenshot/screenshots3/img_2.png',
             '/projects/screenshot/screenshots3/img_3.png',
             '/projects/screenshot/screenshots3/img_4.png',
             '/projects/screenshot/screenshots3/img_5.png',
             '/projects/screenshot/screenshots3/img_6.png',
             '/projects/screenshot/screenshots3/img_7.png',
             '/projects/screenshot/screenshots3/img_8.png',
             '/projects/screenshot/screenshots3/img_9.png',
         ],
         architecture: [
             '/projects/architectures/arch5.png',
         ],
         github: 'https://github.com/HajarAitAbdielmomin/Selection-and-Admission-Process-to-an-engineering-school', live: '#',
     },
        {
            title: 'Course Management System',
            description: 'Course Management Platform is a web application developed as a final-year project for a Bachelor\'s degree in Mathematics & Computer Science at Ibn Tofail University, Kenitra. The platform manages academic resources within the Faculty of Sciences, including courses, modules, practical work (TP), tutorials (TD), and their corrections centralizing content management for both students and faculty staff.',
            tags: ['Python', 'Django', 'HTML', 'CSS', 'JavaScript', 'Bootstrap', 'Sass', 'JQuery', 'MySql', 'MVT', 'Heroku'],
            screenshots: [
                '/projects/screenshot/screenshots1/img.png',
                '/projects/screenshot/screenshots1/img_5.png',
                '/projects/screenshot/screenshots1/img_6.png',
                '/projects/screenshot/screenshots1/img_7.png',
                '/projects/screenshot/screenshots1/img_8.png',
                '/projects/screenshot/screenshots1/img_9.png',
                '/projects/screenshot/screenshots1/img_10.png',
                '/projects/screenshot/screenshots1/img_11.png',
                '/projects/screenshot/screenshots1/img_12.png',
                '/projects/screenshot/screenshots1/img_13.png',
                '/projects/screenshot/screenshots1/img_14.png',
                '/projects/screenshot/screenshots1/img_15.png',
                '/projects/screenshot/screenshots1/img_16.png',
                '/projects/screenshot/screenshots1/img_17.png',
                '/projects/screenshot/screenshots1/img_18.png',
                '/projects/screenshot/screenshots1/img_19.png',
                '/projects/screenshot/screenshots1/img_20.png',
                '/projects/screenshot/screenshots1/img_21.png',
            ],
            architecture: [
                '/projects/architectures/arch2.png',
            ],
            github: 'https://github.com/HajarAitAbdielmomin/Course-Management-System', live: '#',
        },
     {
         title: 'Fully Integrated School Management System',
         description: 'Student Management System Developed as a final-year project for Higher Technician Certificate, a web-based application to centralize and manage academic and personal information for students, while providing teachers with tools to efficiently manage their courses. The system enables the administration of users, students, classes, specialties, modules, and academic units, as well as the management of student grades and continuous assessment schedules. It provides students with access to their grades, exam results, class information, and personal details, while facilitating academic management and supporting the learning process.',
         tags: ['Java', 'JEE', 'HTML', 'CSS', 'JSTL', 'JSP', 'Tomcat','JavaScript', 'Bootstrap', 'UML', 'MySql', 'MVC', 'DAO'],
         screenshots: [
             '/projects/screenshot/screenshots2/img.png',
             '/projects/screenshot/screenshots2/img_1.png',
             '/projects/screenshot/screenshots2/img_2.png',
             '/projects/screenshot/screenshots2/img_3.png',
             '/projects/screenshot/screenshots2/img_4.png',
             '/projects/screenshot/screenshots2/img_5.png',
             '/projects/screenshot/screenshots2/img_6.png',
             '/projects/screenshot/screenshots2/img_7.png',
             '/projects/screenshot/screenshots2/img_8.png',
             '/projects/screenshot/screenshots2/img_9.png',
             '/projects/screenshot/screenshots2/img_10.png',
             '/projects/screenshot/screenshots2/img_11.png',
             '/projects/screenshot/screenshots2/img_12.png',
             '/projects/screenshot/screenshots2/img_13.png',
             '/projects/screenshot/screenshots2/img_14.png',
             '/projects/screenshot/screenshots2/img_15.png',
             '/projects/screenshot/screenshots2/img_16.png',
             '/projects/screenshot/screenshots2/img_17.png',
             '/projects/screenshot/screenshots2/img_18.png',
             '/projects/screenshot/screenshots2/img_19.png',
             '/projects/screenshot/screenshots2/img_20.png',
             '/projects/screenshot/screenshots2/img_21.png',
             '/projects/screenshot/screenshots2/img_22.png',
             '/projects/screenshot/screenshots2/img_23.png',
         ],
         architecture: [
             '/projects/architectures/arch3.png',
             '/projects/architectures/arch4.png',
         ],
         github: 'https://github.com/HajarAitAbdielmomin/School-management-system', live: '#',
     },
     {
         title: 'Rhythmic Revelations: Analyzing Spotify\'s Songs Patterns',
         description: 'A comprehensive BigQuery-based analytics project showcasing data loading, exploration, complex querying, aggregation, conditional filtering, DML operations, and data quality checks all within Google Cloud\'s serverless data warehouse environment.',
         tags: ['BigQuery', 'GCP', 'Cloud', 'BigData', 'Query'],
         screenshots: [
             '/projects/video/demo2.mp4',
         ],
         architecture: [
             '/projects/architectures/arch6.png',
         ],
         github: 'https://github.com/HajarAitAbdielmomin/Analyzing-Spotify-Dataset-with-BigQuery', live: '#',
     },
     {
         title: 'Spring AI model comparator OpenAI-Ollama-Claude',
         description: 'A full-stack application that sends a single user prompt to OpenAI, Anthropic, and a locally running Ollama model at the same time. It displays the three responses side by side, making it easy to compare model behavior, response time, and approximate token usage.',
         tags: ['Java', 'Spring Boot', 'Spring AI', 'OpenAI API', 'Anthropic API', 'Ollama API', 'ReactJs', 'Vite'],
         screenshots: [
             '/projects/video/demo3.mp4',
         ],
         architecture: [
             '/projects/architectures/arch7.png',
         ],
         github: 'https://github.com/HajarAitAbdielmomin/Spring-AI-model-comparator_OpenAI-Ollama-Claude', live: '#',
     },
     {
         title: 'Personal Blog Website',
         description: 'This is a personal blog showcase built with Next.js and React. It pulls recent posts from a Medium RSS feed, lets visitors search and paginate through them, and includes a validated contact form that emails the site owner via Gmail.',
         tags: ['NextJs', 'TypeScript', 'JSON','API', 'Nodemailer','Medium RSS', 'TailwindCss'],
         screenshots: [
             '/projects/screenshot/screenshots4/img1.png',
             '/projects/screenshot/screenshots4/img2.png',
         ],
         architecture: [
             '/projects/architectures/arch8.png',
         ],
         github: 'https://github.com/HajarAitAbdielmomin/personal-blog-website', live: '#',
     },
    ];
export const skillGroups = [

            { index: 0, name: 'Java', icon: FaJava, color: '#007396' },
            { index: 1, name: 'Spring Boot', icon: SiSpringboot, color: '#6DB33F' },
            { index: 2, name: 'Spring Security', icon: SiSpring, color: '#6DB33F' },
            { index: 3, name: 'Spring AI', icon: TbBrandOpenai, color: '#6DB33F' },
            { index: 4, name: 'REST APIs', icon: TbApi, color: '#374151' },

            { index: 5, name: 'ReactJS', icon: SiReact, color: '#61DAFB' },
            { index: 6, name: 'Next.js', icon: SiNextdotjs, color: '#000000' },
            { index: 7, name: 'Angular', icon: SiAngular, color: '#DD0031' },
            { index: 8, name: 'TypeScript', icon: SiTypescript, color: '#3178C6' },
            { index: 9, name: 'MySQL', icon: SiMysql, color: '#4479A1' },


            { index: 10, name: 'AWS', icon: TbBrandAws, color: '#FF9900' },
            { index: 11, name: 'Docker', icon: SiDocker, color: '#2496ED' },
            { index: 12, name: 'Git', icon: SiGit, color: '#F05032' },
            { index: 13, name: 'Swagger', icon: SiSwagger, color: '#85EA2D' },

];
export const certificationsData: Certification[] = [

    {
        id: '1',
        organizationName: 'Oracle',
        organizationLogo: '/logo/organizations/oracle.png',
        courseName: 'Oracle Certified Professional: Java SE 17 Developer',
        certificationImage: '/certificates/java17.jpg',
    },
    {
        id: '2',
        organizationName: 'Huawei',
        organizationLogo: '/logo/organizations/huawei.png',
        courseName: 'Huawei Certified Specialist Associate Sales-IP Network',
        certificationImage: '/certificates/huawei.jpg',
    },
    {
        id: '3',
        organizationName: 'Simplilearn',
        organizationLogo: '/logo/organizations/simplilearn.jpg',
        courseName: 'Getting Started with JUnit',
        certificationImage: '/certificates/junit.jpg',
    },
    {
        id: '4',
        organizationName: 'Coursera - AWS',
        organizationLogo: '/logo/organizations/coursera.jpg',
        courseName: 'AWS Cloud Technical Essentials',
        certificationImage: '/certificates/aws.jpg',
    },
    {
        id: '5',
        organizationName: 'LinkedIn Learning',
        organizationLogo: '/logo/organizations/linkedin.jpg',
        courseName: 'GitHub Career Essentials – Professional Certificate',
        certificationImage: '/certificates/github.jpg',
    },

    {
        id: '6',
        organizationName: 'Coursera',
        organizationLogo: '/logo/organizations/coursera.jpg',
        courseName: 'Introduction to Test Automation with Selenium and Java',
        certificationImage: '/certificates/selenium.jpg',
    },
    {
        id: '7',
        organizationName: 'Simplilearn',
        organizationLogo: '/logo/organizations/simplilearn.jpg',
        courseName: 'Angular Basics',
        certificationImage: '/certificates/angular.jpg',
    },
    {
        id: '8',
        organizationName: 'Coursera',
        organizationLogo: '/logo/organizations/coursera.jpg',
        courseName: 'Building CI/CD Pipelines with Jenkins (Declarative & IaC)',
        certificationImage: '/certificates/jenkins.jpg',
    },
    {
        id: '9',
        organizationName: 'Simplilearn',
        organizationLogo: '/logo/organizations/simplilearn.jpg',
        courseName: 'Containerization Basics with Docker',
        certificationImage: '/certificates/docker.jpg',
    },
    {
        id: '10',
        organizationName: 'Oracle',
        organizationLogo: '/logo/organizations/oracle.png',
        courseName: 'Oracle Certified Professional: Java SE 21 Developer',
        certificationImage: '/certificates/java21.jpg',
    },
    {
        id: '11',
        organizationName: 'Coursera',
        organizationLogo: '/logo/organizations/coursera.jpg',
        courseName: 'Working with BigQuery for fast data analysis',
        certificationImage: '/certificates/bigQuery.jpg',
    },
    {
        id: '12',
        organizationName: 'Forage',
        organizationLogo: '/logo/organizations/forage.png',
        courseName: 'Skyscanner Front-End Software Engineering virtual experience programme on Forage',
        certificationImage: '/certificates/skyscanner.jpg',
    },
    {
        id: '13',
        organizationName: 'Hackerrank',
        organizationLogo: '/logo/organizations/Hackerrank.png',
        courseName: 'Java Fundamentals & Problem Solving Certification',
        certificationImage: '/certificates/Hackerrank1.jpg',
    },
];

export const educationsData: Education[] = [
    {
        logo: '/logo/school-logo/bts.png',
        schoolName: 'Ibn Sina Technical High School - BTS',
        location: 'Kenitra, Morocco',
        degree: 'Higher Technician Certificate',
        major: 'Information System Development',
        startYear: '2018',
        endYear: '2020',
        isGraduated: true,
    },
    {
        logo: '/logo/school-logo/UIT.png',
        schoolName: 'Ibn Tofail University - Faculty of Sciences',
        location: 'Kenitra, Morocco',
        degree: 'Bachelor’s Degree',
        major: 'Mathematics & Computer Sciences',
        startYear: '2020',
        endYear: '2021',
        isGraduated: true,
    },
    {
        logo: '/logo/school-logo/ensa.png',
        schoolName: 'The National School of Applied Sciences',
        location: 'Berrechid, Morocco',
        degree: 'Engineer’s Degree',
        major: 'Computer Engineering',
        startYear: '2021',
        endYear: '2024',
        isGraduated: true,
    },
];

export const internshipsData: Internship[] = [
    {
        id: '1',
        position: 'Software Engineer Intern',
        company: 'Capgemini Engineering',
        companyLogo: '/logo/companies/cap.png',
        location: 'Casablanca, Morocco',
        startDate: 'Fev 2024',
        endDate: 'Jun 2024',
        status: 'completed',
        topic: 'Digitalization Of the Onboarding Process for New Hires and Monitoring the Skill Development of Capgemini Consultants: « Welcome In » Platform',
        tasks: [],
        technologies: ['Figma', 'NextJs', 'NodeJs', 'TailwindCss', 'MUI', 'TypeScript', 'NodeMailer','Strapi CMS', 'AWS', 'Docker', 'UML', 'BPMN', 'MySql', 'JWT', 'Agile/Scrum'],
        uiImages: [
            '/images/cap-project/ui-work-1.png',
            '/images/cap-project/ui-work-2.png',
            '/images/cap-project/ui-work-3.png',
            '/images/cap-project/ui-work-4.png',
            '/images/cap-project/ui-work-5.png',
            '/images/cap-project/ui-work-6.png',
            '/images/cap-project/ui-work-7.png',
            '/images/cap-project/ui-work-8.png',
            '/images/cap-project/ui-work-9.png',
            '/images/cap-project/ui-work-10.png',
            '/images/cap-project/ui-work-11.png',
            '/images/cap-project/ui-work-12.png',
            '/images/cap-project/ui-work-13.png',
            '/images/cap-project/ui-work-14.png',
            '/images/cap-project/ui-work-15.png',
        ],
        width: 40,
        height: 40,
    },
    {
        id: '2',
        position: 'Software Engineer - Spring-boot/ReactJs',
        company: 'Info Etoile',
        companyLogo: '/logo/companies/info-etoile.png',
        location: 'Kenitra, Morocco',
        startDate: 'Jul 2023',
        endDate: 'Sep 2023',
        status: 'completed',
        topic: 'Integrated Management of Jobs and Recruitment Process, « CareerHub » Platform',
        tasks: [],
        technologies: ['UML', 'ReactJS', 'Spring boot', 'Spring security', 'JDK17','Bootstrap', 'Axios', 'MySql'],
        uiImages: [
            '/images/info-project/ui-work-1.png',
            '/images/info-project/ui-work-2.png',
            '/images/info-project/ui-work-3.png',
            '/images/info-project/ui-work-4.png',
            '/images/info-project/ui-work-5.png',
            '/images/info-project/ui-work-6.png',
            '/images/info-project/ui-work-7.png',
            '/images/info-project/ui-work-8.png',
            '/images/info-project/ui-work-9.png',
            '/images/info-project/ui-work-10.png',
            '/images/info-project/ui-work-11.png',
            '/images/info-project/ui-work-12.png',
            '/images/info-project/ui-work-13.png',
            '/images/info-project/ui-work-14.png',
        ],
        width: 90,
        height: 90,
    },
    {
        id: '3',
        position: 'Web Developer - PHP/Laravel',
        company: 'Web Eco',
        companyLogo: '/logo/companies/webeco.png',
        location: 'Kenitra, Morocco',
        startDate: 'Jul 2022',
        endDate: 'Aug 2022',
        status: 'completed',
        topic: 'IT Ticketing System',
        tasks: [],
        technologies: ['Laravel', 'PHP', 'HTML', 'CSS', 'JQuery', 'JavaScript', 'MySql', 'PhpMyAdmin'],
        uiImages: [
            '/images/webeco-project/ui-work-1.png',
            '/images/webeco-project/ui-work-2.png',
            '/images/webeco-project/ui-work-3.png',
            '/images/webeco-project/ui-work-4.png',
            '/images/webeco-project/ui-work-5.png',
            '/images/webeco-project/ui-work-6.png',
            '/images/webeco-project/ui-work-1-6.png',
            '/images/webeco-project/ui-work-2-6.png',
            '/images/webeco-project/ui-work-7.png',
            '/images/webeco-project/ui-work-8.png',
            '/images/webeco-project/ui-work-9.png',
            '/images/webeco-project/ui-work-10.png',
            '/images/webeco-project/ui-work-11.png',
            '/images/webeco-project/ui-work-12.png',
            '/images/webeco-project/ui-work-13.png',
            '/images/webeco-project/ui-work-14.png',
        ],
        width: 60,
        height: 40,
    },
    {
        id: '4',
        position: 'Web developer — PHP',
        company: 'The court of appeal',
        companyLogo: '/logo/companies/courDappel.png',
        location: 'Kenitra, Morocco',
        startDate: 'Jul 2019',
        endDate: 'Aug 2019',
        status: 'completed',
        topic: 'Internal Library Management System',
        tasks: [
            'Creating micro-interactions',
            'Transition animations',
            'Performance optimization',
            'Animation documentation',
        ],
        technologies: ['Merise', 'PhpMyAdmin', 'PHP', 'CSS', 'HTML'],
        uiImages: [
            '/images/court-project/ui-work-1.jpg',
            '/images/court-project/ui-work-2.jpg',
            '/images/court-project/ui-work-3.jpg',
            '/images/court-project/ui-work-4.jpg',
        ],
        width: 40,
        height: 40,
    },
];